apiVersion: apps/v1
kind: Deployment
metadata:
  name: diploma-app
  labels:
    env: develop
    app: main
    tier: python
    owner: NorD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diploma-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: diploma-app
    spec:
      containers:
        - name: diploma-app
          image: nordz0r/epam24_diplom:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
          - name: db_host
            value: mysql.cw1htr89vlre.eu-north-1.rds.amazonaws.com
          - name: db_user
            value: covid
          - name: db_password
            value: laserdisk
          - name: db_database
            value: covid
