name: App Building and Ci/CD

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nordz0r
            -Dsonar.projectKey=nordz0r_epam24_diplom
            -Dsonar.python.version=3.9
            -Dsonar.python.coverage.reportPaths=pycoverage.xml
  Build:
    needs: [SonarCloud]
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: ${{ github.event.repository.name }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: |
        cd app
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$(date +%s) .
    - name: Docker Push
      run: docker push -a $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
