name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  DOCKERHUB_REPO: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Debug
      run: |
        echo "$GITHUB_CONTEXT"
        env
        ls -lha
    - name: Login to DockerHub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: |
        cd app
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$(date +%s) .
    - name: Docker Push
      run: docker push -a $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest