name: App Building and Ci/CD for feature

on:
  push:
    branches: [ feature ]
    paths:
      - 'app/**'
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:


jobs:
  SonarCloud:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=nordz0r
            -Dsonar.projectKey=nordz0r_epam24_diplom
            -Dsonar.python.version=3.9
            -Dsonar.python.coverage.reportPaths=pycoverage.xml
  Build-backend:
    needs: [SonarCloud]
    runs-on: ubuntu-latest
    environment: dev
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: "covapp-backend"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: |
        cd app/backend
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$(date +%s) .
    - name: Docker Push
      run: docker push -a $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
  Build-frontend:
    needs: [SonarCloud]
    environment: dev
    runs-on: ubuntu-latest
    environment: dev
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: "covapp-frontend"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to DockerHub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: |
        cd app/frontend
        docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$(date +%s) .
    - name: Docker Push
      run: docker push -a $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
